# Generated by Django 3.2.12 on 2022-07-02 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('to_the_department', models.CharField(blank=True, choices=[('Support & Helpdesk Department', 'Support & Helpdesk Department'), ('Report & Feedback Department', 'Report & Feedback Department'), ('Customer Support Department', 'Customer Support Department'), ('Accounts Department', 'Accounts Department'), ('Share your Knowledge', 'Share your Knowledge')], max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('Subscription', models.CharField(blank=True, choices=[('Build Business Profile', 'Build Business Profile'), ('Free E-books & Updates', 'Free E-books & Updates'), ('Free Sessions & Newsletter', 'Free Sessions & Newsletter'), ('Send me all Updates', 'Send me all Updates')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Think',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
