# Generated by Django 3.2.12 on 2022-07-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='to_the_department',
            field=models.CharField(blank=True, choices=[('Support & Helpdesk Department', 'Support & Helpdesk Department'), ('Report & Feedback Department', 'Report & Feedback Department'), ('Customer Support Department', 'Customer Support Department'), ('In-appropiate Content Report', 'In-appropiate Content Report'), ('Other Reason', 'Other Reason')], max_length=30, null=True),
        ),
    ]
