# Generated by Django 3.2.12 on 2022-07-02 02:33

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.FileField(blank=True, null=True, upload_to='media')),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='author')),
                ('feeling', models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Inspired', 'Inspired'), ('Bored', 'Bored'), ('Empty', 'Empty'), ('Anger', 'Anger'), ('Crying', 'Crying'), ('Blessed', 'Blessed'), ('Awesome', 'Awesome'), ('Cool', 'Cool'), ('like a kid', 'like a kid'), ('like a boss', 'like a boss'), ('Tired', 'Tired'), ('Broken', 'Broken'), ('Lonely', 'Lonely')], max_length=100, null=True)),
                ('activity', models.CharField(blank=True, choices=[('Dancing', 'Happy'), ('Cooking', 'Sad'), ('Reading', 'Inspired'), ('Walking', 'Bored'), ('Watching', 'Watching'), ('Playing', 'Playing'), ('Working', 'Working'), ('Work-out', 'Work-out')], max_length=100, null=True)),
                ('like_count', models.BigIntegerField(default='0')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=50)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='videolike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocomment', to='post.video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('reaction', models.CharField(blank=True, choices=[('Nice', 'Nice'), ('Great', 'Great'), ('Innovative', 'Innovative'), ('So what', 'So what'), ('Trash', 'Trash'), ('Why doing this ?', 'Why doing this ?'), ('Happy for you', 'Happy for you'), ('Thanks', 'Thanks'), ('kya majburi thi bhai ?', 'kya majburi thi bhai ?'), ('Cool', 'Cool')], max_length=100, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
