# Generated by Django 3.2.12 on 2022-07-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
    ]
