# Generated by Django 3.2.12 on 2022-07-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_video_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='activity',
            field=models.CharField(blank=True, choices=[('Dancing', 'Happy'), ('Cooking', 'Sad'), ('Reading', 'Inspired'), ('Walking', 'Bored'), ('Watching', 'Watching'), ('Playing', 'Playing'), ('Working', 'Working'), ('Work-out', 'Work-out'), ('Thinking', 'Thinking'), ('Sleeping', 'Sleeping'), ('Dreaming', 'Dreaming')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='reaction',
            field=models.CharField(blank=True, choices=[('Nice', 'Nice'), ('Great', 'Great'), ('Innovative', 'Innovative'), ('So what', 'So what'), ('Trash', 'Trash'), ('Why doing this ?', 'Why doing this ?'), ('Happy for you', 'Happy for you'), ('Thanks', 'Thanks'), ('Kya majburi thi bhai ?', 'Kya majburi thi bhai ?'), ('Cool', 'Cool')], max_length=100, null=True),
        ),
    ]
