# Generated by Django 3.2.12 on 2022-07-02 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Single', 'Single'), ('Engaged', 'Engaged'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Complicated', 'Complicated'), ('Lover', 'Lover'), ('I am Awesome', 'I am Awesome')], max_length=30, null=True)),
                ('academicbackground', models.CharField(blank=True, choices=[('Class 6th', 'Class 6th'), ('Class 7th', 'Class 7th'), ('Class 8th', 'Class 8th'), ('Class 9th', 'Class 9th'), ('High-School', 'High-School'), ('High-School+', 'High-School+'), ('Intermediate', 'Intermediate'), ('Pursuing Undergraduate', 'Pursuing Undergraduate'), ('Pursuing Post-Undergraduate', 'Pursuing Post-Undergraduate'), ('Undergraduate', 'Undergraduate'), ('Post-Undergraduate', 'Post-Undergraduate'), ('Self Learner', 'Self Learner')], max_length=40, null=True)),
                ('school_name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, choices=[('India', 'India'), ('Europe Continent', 'Europe Continent'), ('Africa Continent', 'Africa Continent'), ('Australia Continent', 'Australia Continent'), ('Asia Continent', 'Asia Continent'), ('North America Continent', 'North America Continent'), ('South America Continent', 'South America Continent')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('Outside Of India', 'Outside of India'), ('India', 'India')], max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunanchal Pradesh'), ('Assam', 'Assam '), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerela', 'Kerela'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh '), ('Maharastra', 'Maharastra '), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', ' Odisha'), ('Punjab', ' Punjab'), ('Puducherry', 'Puducherry'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Naidu', 'Tamil Naidu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default='uploads/profile_pictures/default.png', null=True, upload_to='uploads/profile_pictures')),
                ('follower', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
