# Generated by Django 3.2.12 on 2022-07-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/Penguins.png', null=True, upload_to='uploads/profile_pictures'),
        ),
    ]
